version: "3"
services:
  vendor-portal1:
    image: 335022/seleniumdocker
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - THREAD_COUNT=3
      - TEST_SUITE=testng_regression.xml
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output
      - ./allure-results:/home/selenium-docker/allure-results